# config.ini (template)
[API]

#discord api
TOKEN = discord api token

#plex api
plexUser = plex account username
plexPass = plex account password
plexServer = plex server name Example: HOME-SERVER

#radarr
host_url = radarr url for api Example: http://private_server_ip:7878/
api_key = radarr api key

#sonarr
sapi_key =  sonar api key
shost_url = sonarr url for api Example: http://private_server_ip:8989

quality_profile = Any
language = English

tmdb_api = the movie database api key

movie_path = where you store you movie files
show_path = where you store your show files

channel_id = discord channel id for messages
